### PR TITLE
futures: heartbeat improvements

### LINKED ISSUE #51: Add support for amqp(s):// URIs
I'm using Lapin on Heroku and had to bodge together some boilerplate for translating the amqp://* URIs that are passed in through env vars. There is an official-ish specification (https://www.rabbitmq.com/uri-spec.html) and other libraries like bunny for Ruby have built-in support. (Though there's mention [here](http://rubybunny.info/articles/connecting.html#using_connection_strings) that there are some implementation differences, but I can't imagine they wouldn't be that hard to paper over). I'd be willing to take this on, but I wanted to raise the issue first and see if anyone had any comments. I could envision this either being a method on ConnectionOptions, or even a separate helper function that returns ConnectionOptions and SockAddr together.

### LINKED ISSUE #54: Failed to send heartbeat error
I'm trying to combine tokio-postgres with lapin-futures(version 0.8.2, using RMQ 3.6.9), the use case is listening to postgres notifications and publishing to a RMQ queue with lapin, this example works:

```rust
fn main() {
  env_logger::init().unwrap();
  let mut core = Core::new().unwrap();
  let handle = core.handle();

  let addr = "127.0.0.1:5672".parse().unwrap();

  core.run(
    TcpStream::connect(&addr, &handle)
      .and_then(|stream| lapin::client::Client::connect(stream, &ConnectionOptions::default()))
      .and_then(|client| client.create_channel())
      .and_then(|channel| {
        channel.queue_declare("hello", &QueueDeclareOptions::default(), FieldTable::new()).and_then(|_| {
          Connection::connect("postgres://postgres@localhost", TlsMode::None, &handle)
          .then(|conn| conn.unwrap().batch_execute("LISTEN pgchannel1").map_err(|_|Error::new(ErrorKind::Other, "")))
          .and_then(|conn|
            conn.notifications().map_err(|_|Error::new(ErrorKind::Other, "")).for_each(move |n|{
              println!("Publishing payload: {}", n.payload);
              channel.basic_publish(
                  "hello",
                  n.payload.as_bytes(),
                  &BasicPublishOptions::default(),
                  BasicProperties::default()
              );
              Ok(())
            })
          )
        })
      })
  ).unwrap();
}
```

But after 3 mins of being idle, the RMQ tcp connection is dropped(disappears from RMQ management web interface), and when trying to send another notification to the queue the following message is shown:

```rust
ERROR:lapin_futures::transport: Failed to send frame: Error { repr: Os { code: 104, message: "Connection reset by peer" } }
ERROR:lapin_futures::transport: Failed to send heartbeat: Error { repr: Os { code: 32, message: "Broken pipe" } }
ERROR:lapin_futures::transport: Failed to send frame: Error { repr: Os { code: 32, message: "Broken pipe" } }
ERROR:lapin_futures::transport: Failed to send frame: Error { repr: Os { code: 32, message: "Broken pipe" } }
ERROR:lapin_futures::transport: upstream poll gave Ready(None)
ERROR:lapin_futures::transport: Failed to send frame: Error { repr: Os { code: 32, message: "Broken pipe" } }
ERROR:lapin_futures::transport: upstream poll gave Ready(None)
```

I've checked and the 3 mins are because of 3 failed heartbeats(60s each one, same error can be obtained faster by reducing heartbeat). 

How can I keep the lapin connection alive while consuming another stream? Any pointers would help. Thanks.

### PR DESCRIPTION
**Pull request by Keruspe**
1) allow users to query the negociated value for heartbeat and stuff
2) actually wait for the negociation to happen before starting the heartbeat, or we'd use the one provided by the user and not the one negociated.
3) Heartbeat is now in a separate thread so that the main one cannot ever block it.
4) We now require the user to actually launch the heartbeat thread (we provide them with a callback that returns the heartbeating future)

Fixes #54 

The README update fixes #51 too

### CODE REVIEW

**Comment by Keruspe** [comment]
Maybe give #64 a look first, as this one will be easier to rebase.

**Comment by Keruspe** [comment]
This is now based on top of #64 

Heartbeat is now in a separate thread so that the main one cannot ever block it.

**Comment by Keruspe** [comment]
We now require the caller to launch the thread themselves, see https://github.com/sozu-proxy/lapin/pull/63/commits/cd0742cc1f8dcf37897773bbfd1a35dc593a4852

File: async/src/connection.rs [hunk 1]
```diff
@@ -89,7 +89,7 @@ pub struct Connection {
   /// next request id
   pub request_index:     RequestId,
   /// list of finished requests
-  pub finished_reqs:     HashSet<RequestId>,
+  pub finished_reqs:     HashMap<RequestId, bool>,
```
Comment (Geal) [inline async/src/connection.rs]: the boolean is not very explicit here, what does it indicate?

File: futures/README.md [hunk 2]
```diff
@@ -43,7 +43,7 @@ fn main() {
       // connect() returns a future of an AMQP Client
       // that resolves once the handshake is done
       lapin::client::Client::connect(stream, &ConnectionOptions::default())
-    }).and_then(|client| {
+    }).and_then(|(client, )| {
```
Comment (Geal) [inline futures/README.md]: what is in that tuple?

File: futures/README.md [hunk 3]
```diff
@@ -96,7 +97,11 @@ fn main() {
       // connect() returns a future of an AMQP Client
       // that resolves once the handshake is done
       lapin::client::Client::connect(stream, &ConnectionOptions::default())
-    }).and_then(|client| {
+    }).and_then(|(client, heartbeat_future_fn)| {
```
Comment (Geal) [inline futures/README.md]: nice and clean :)

Comment (Geal) [inline futures/README.md]: maybe add some comments to explain why the heartbeat needs to run in its own thread

File: futures/src/channel.rs [hunk 4]
```diff
@@ -119,596 +126,298 @@ pub struct QueueDeleteOptions {
...
-      if let Some(message) = transport.conn.next_get_message(channel_id, &queue) {
-        Ok(Async::Ready(message))
-      } else {
-        transport.poll()?;
-        trace!("basic get[{}-{}] not ready", channel_id, queue);
-        Ok(Async::NotReady)
-      }
-    } else {
-      return Ok(Async::NotReady);
+    fn run_on_locked_transport_full<Action, Finished>(&self, method: &str, error: &str, action: Action, finished: Finished, payload: Option<(u16, &[u8], BasicProperties)>) -> Box<Future<Item = Option<bool>, Error = io::Error>>
```
Comment (Geal) [inline futures/src/channel.rs]: that's a great refactoring!

File: futures/src/lib.rs [hunk 5]
```diff
@@ -95,7 +96,11 @@
 //!       // connect() returns a future of an AMQP Client
 //!       // that resolves once the handshake is done
 //!       lapin::client::Client::connect(stream, &ConnectionOptions::default())
-//!     }).and_then(|client| {
+//!    }).and_then(|(client, heartbeat_future_fn)| {
```
Comment (Geal) [inline futures/src/lib.rs]: same here, explain why we need to put the heartbeat in a separate thread

File: async/src/connection.rs (hunk 1 above)
Comment (Keruspe) [inline async/src/connection.rs]: I should add a comment there, but it's there only to mimic what's done for finished_get_reqs so that both can be handled exactly the same way. In the case of finished_reqs it's actually always true, it's just a matter of unifying the two.
I thought of even merging the two, but i left them separated for now.

File: futures/README.md (hunk 2 above)
Comment (Keruspe) [inline futures/README.md]: The callback which returns the heartbeat future

Comment (Keruspe) [inline futures/README.md]: I made that a tuple so that you have to either deal with it or explicitely ignore it, instead of it being hidden and easily forgettable

Comment (Geal) [inline futures/README.md]: that code does not really make it explicit :)

Comment (Geal) [inline futures/README.md]: and shouldn't that be `(client, _)` to ignore it instead? Or is that a syntax I didn't know about

File: futures/src/lib.rs (hunk 5 above)
Comment (Keruspe) [inline futures/src/lib.rs]: We need to put the heartbeat in a separate thread to deal with issues like #54 where the "main" thread could be in a state where it does nothing until it gets data from stdin or such.

File: futures/README.md (hunk 3 above)
Comment (Keruspe) [inline futures/README.md]: Yup, will do

File: async/src/connection.rs (hunk 1 above)
Comment (Geal) [inline async/src/connection.rs]: then maybe finished_get_reqs should be made more explicit too ;)

File: futures/README.md (hunk 2 above)
Comment (Keruspe) [inline futures/README.md]: huh, there sure should be an underscore there, probably a vim-typo.

File: futures/src/lib.rs (hunk 5 above)
Comment (Geal) [inline futures/src/lib.rs]: I know that :) But people who will copy that code do not

File: async/src/connection.rs (hunk 1 above)
Comment (Keruspe) [inline async/src/connection.rs]: Will add comments for both

File: async/src/connection.rs [hunk 6]
```diff
@@ -89,8 +89,10 @@ pub struct Connection {
   /// next request id
   pub request_index:     RequestId,
   /// list of finished requests
+  /// value is true if the requets returned something or false otherwise
```
Comment (Geal) [inline async/src/connection.rs]: "requets"

File: README.md [hunk 7]
```diff
@@ -60,3 +60,9 @@ Then include it in your code like this:
 #[macro_use]
 extern crate lapin_async;
 ```
+
+## TLS integration
```
Comment (Geal) [inline README.md]: :+1:

**Comment by Geal** [comment]
Thanks!
