### PR TITLE
Notify task when Consumer was cancelled or error was set

### LINKED ISSUE #222: Consumer does not poll stream after error
In `lapin v0.28.3` with `futures` feature, await-ing on a consumer stream can hang forever when the connection to RabbitMQ fails. 

Does `Consumer::set_error` wakes the pending task?

Last log after I kill the connection with `tcpkill`:
```
[2019-11-25T12:59:28Z TRACE lapin::consumer::futures] consumer poll; polling transport
[2019-11-25T12:59:28Z TRACE lapin::consumer::futures] consumer poll; acquired inner lock, consumer_tag=xxx
[2019-11-25T12:59:28Z TRACE lapin::consumer::futures] delivery; status=NotReady, consumer_tag=xxx
[2019-11-25T12:59:28Z TRACE lapin::io_loop] io_loop poll done
[2019-11-25T12:59:28Z TRACE lapin::io_loop] io_loop do_run; can_read=true, can_write=true, has_data=false
[2019-11-25T12:59:28Z ERROR lapin::io_loop] error reading: IOError(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })
[2019-11-25T12:59:28Z ERROR lapin::connection] Connection error
[2019-11-25T12:59:28Z TRACE lapin::consumer] set_error; consumer_tag=xxx
[2019-11-25T12:59:28Z TRACE lapin::consumer] cancel; consumer_tag=xxx
```

### PR DESCRIPTION
**Pull request by denzp**
The change fixes `Consumer` behaviour when a connection error happened. It's important to wake up the task because otherwise, user code will never receive the error.

Closes #222

### CODE REVIEW

File: src/consumer.rs [hunk 1]
```diff
@@ -186,6 +186,7 @@ impl ConsumerInner {
 
     fn cancel(&mut self) -> Result<()> {
         trace!("cancel; consumer_tag={}", self.tag);
+        self.drop_deliveries();
```
Comment (Keruspe) [inline src/consumer.rs]: Any reason to move this earlier?

File: src/consumer.rs [hunk 2]
```diff
@@ -211,7 +213,10 @@ impl ConsumerInner {
                 .send(Err(error))
                 .expect("failed to send error to consumer");
         }
-        self.cancel()
+        if let Some(ref task) = self.task {
+            task.notify();
+        }
+        Ok(())
```
Comment (Keruspe) [inline src/consumer.rs]: Does this really need to be changed? I don't think sending an extra Ok(None) after the error is a problem, and it brings consistency wrt Ok(None) being the marker for finishing a stream

File: src/consumer.rs (hunk 1 above)
Comment (denzp) [reply src/consumer.rs]: Yes, it's actually important. `drop_deliveries` cleans the consumer channel. Unfortunately `Ok(None)` is also being purged and in the stream polling, this leads to `delivery; status=NotReady`.

File: src/consumer.rs (hunk 2 above)
Comment (denzp) [reply src/consumer.rs]: The problem is that `cancel` method clears the consumer channel and the messages we just send there getting erased before `Stream::poll_next` has a chance to receive it.

**Comment by denzp** [comment]
Thanks for reviewing! I've rebased the commit and changed MR target branch.

File: src/consumer.rs (hunk 2 above)
Comment (denzp) [reply src/consumer.rs]: Also, I have a feeling, it's better to serve pending messages in the consumer channel before the error, instead of discarding them (`cancel` behaviour atm).

**Comment by Keruspe** [comment]
I want to give #223 a shot and I'll make a release after that
